<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MD_HDT6</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="MD_HDT6_files/libs/clipboard/clipboard.min.js"></script>
<script src="MD_HDT6_files/libs/quarto-html/quarto.js"></script>
<script src="MD_HDT6_files/libs/quarto-html/popper.min.js"></script>
<script src="MD_HDT6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MD_HDT6_files/libs/quarto-html/anchor.min.js"></script>
<link href="MD_HDT6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MD_HDT6_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MD_HDT6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MD_HDT6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MD_HDT6_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MD_HDT6</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"train.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="dvisión-de-variables-numéricas-y-obtención-de-data-de-prueba-y-entrenamiento" class="level2">
<h2 class="anchored" data-anchor-id="dvisión-de-variables-numéricas-y-obtención-de-data-de-prueba-y-entrenamiento">1. Dvisión de variables numéricas y obtención de data de prueba y entrenamiento</h2>
<section id="división-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="división-de-variables">1.1 División de variables</h3>
<div class="cell">

</div>
</section>
<section id="analisis-de-nas" class="level3">
<h3 class="anchored" data-anchor-id="analisis-de-nas">1.2 Analisis de NA’s</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>faltantes_por_col <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(datos))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>faltantes_por_col</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                                      
            0             0             0             0             0 
                                                                      
            0             0             0             0             0 
                                                                      
            0             0             0             0             0 
                                                                      
            0             0             0             0             0 
                                                                      
            0             0             0             0             0 
                                                                      
            0             0             0             0             0 
                         Id    MSSubClass      MSZoning        Street 
            0             0             0             0             0 
        Alley      LotShape   LandContour     Utilities     LotConfig 
         1110             0             0             0             0 
    LandSlope  Neighborhood    Condition1    Condition2      BldgType 
            0             0             0             0             0 
   HouseStyle     YearBuilt  YearRemodAdd     RoofStyle      RoofMatl 
            0             0             0             0             0 
  Exterior1st   Exterior2nd    MasVnrType     ExterQual     ExterCond 
            0             0             0             0             0 
   Foundation      BsmtQual      BsmtCond  BsmtExposure  BsmtFinType1 
            0            31            31            32            31 
 BsmtFinType2       Heating     HeatingQC    CentralAir    Electrical 
           32             0             0             0             1 
  KitchenQual    Functional   FireplaceQu    GarageType   GarageYrBlt 
            0             0           596            74            74 
 GarageFinish    GarageQual    GarageCond    PavedDrive        PoolQC 
           74            74            74             0          1189 
        Fence   MiscFeature        MoSold        YrSold      SaleType 
          967          1156             0             0             0 
SaleCondition 
            0 </code></pre>
</div>
</div>
<p>Se puede observar que PoolQC tiene demasiados datos faltantes, al igual que Fence, Alley, MiscFeature y FireplaceQu. Por lo tanto estas columnas no se usaran.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">select</span>(datos, <span class="sc">-</span>Id, <span class="sc">-</span>PoolQC, <span class="sc">-</span>Fence, <span class="sc">-</span>Alley, <span class="sc">-</span>MiscFeature, <span class="sc">-</span>FireplaceQu)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="eliminación-de-variables-no-significativas" class="level3">
<h3 class="anchored" data-anchor-id="eliminación-de-variables-no-significativas">1.2 Eliminación de variables no significativas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">select</span>(datos, <span class="sc">-</span>GarageYrBlt, <span class="sc">-</span>SaleType, <span class="sc">-</span>SaleCondition, <span class="sc">-</span>MoSold, <span class="sc">-</span>YrSold, <span class="sc">-</span>YearBuilt, <span class="sc">-</span>Condition2, <span class="sc">-</span>MSSubClass, MSZoning, <span class="sc">-</span>LotShape, <span class="sc">-</span>YearRemodAdd, <span class="sc">-</span>Exterior1st, <span class="sc">-</span>BsmtFinType1, <span class="sc">-</span>BsmtFinType2, <span class="sc">-</span>GarageQual, <span class="sc">-</span>GarageCond, <span class="sc">-</span>RoofMatl, <span class="sc">-</span>Condition1, <span class="sc">-</span>BsmtQual, <span class="sc">-</span>Exterior2nd, <span class="sc">-</span>RoofStyle, <span class="sc">-</span>GarageType)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Se observaron diferentes variables que no aportaban al modelo, por lo tanto se decidió eliminarlas.</p>
</section>
<section id="creación-de-clasificación-de-la-variable-de-precios" class="level3">
<h3 class="anchored" data-anchor-id="creación-de-clasificación-de-la-variable-de-precios">1.3 Creación de clasificación de la variable de precios</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>p33 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(datos<span class="sc">$</span>SalePrice, <span class="fl">0.33</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>p66 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(datos<span class="sc">$</span>SalePrice, <span class="fl">0.66</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>datosT <span class="ot">&lt;-</span> datos</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>datosT <span class="ot">&lt;-</span> datosT <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">clasificacion =</span> <span class="fu">ifelse</span>(datosT<span class="sc">$</span>SalePrice <span class="sc">&lt;</span> p33, <span class="st">"Economicas"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ifelse</span>(datosT<span class="sc">$</span>SalePrice <span class="sc">&lt;</span> p66, <span class="st">"Intermedias"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Caras"</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>datosT<span class="sc">$</span>clasificacion <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(datosT<span class="sc">$</span>clasificacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creación-de-variables-dicotómicas" class="level3">
<h3 class="anchored" data-anchor-id="creación-de-variables-dicotómicas">1.4 Creación de variables dicotómicas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>datos_con_dummy <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(datosT, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">"clasificacion"</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>datos_con_dummy <span class="ot">&lt;-</span> <span class="fu">select</span>(datos_con_dummy, <span class="sc">-</span>clasificacion, <span class="sc">-</span>clasificacion_Economicas, <span class="sc">-</span>clasificacion_Intermedias)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>datos_con_dummy<span class="sc">$</span>clasificacion_Caras <span class="ot">&lt;-</span> datos_con_dummy<span class="sc">$</span>clasificacion_Caras</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>datos_con_dummy <span class="ot">&lt;-</span> datos_con_dummy <span class="sc">%&gt;%</span> <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"clasificacion_Caras"</span>), as.factor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="datos-de-entrenamiento-y-prueba" class="level3">
<h3 class="anchored" data-anchor-id="datos-de-entrenamiento-y-prueba">2. Datos de entrenamiento y prueba</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>datos_num <span class="ot">&lt;-</span> <span class="fu">select</span>(datos_con_dummy, <span class="sc">-</span>SalePrice)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>datos_num <span class="ot">&lt;-</span> <span class="fu">select</span>(datos_con_dummy, <span class="sc">-</span>Utilities)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(datos_num), <span class="fu">nrow</span>(datos_num) <span class="sc">*</span> porcentaje)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> datos_num[corte, ]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> datos_num[<span class="sc">-</span>corte, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="modelo-de-regresión-logística-para-saber-si-vivienda-es-cara-o-no." class="level2">
<h2 class="anchored" data-anchor-id="modelo-de-regresión-logística-para-saber-si-vivienda-es-cara-o-no.">3. Modelo de regresión logística para saber si vivienda es cara o no.</h2>
<section id="modelo-con-todas-las-variables." class="level3">
<h3 class="anchored" data-anchor-id="modelo-con-todas-las-variables.">3.1 Modelo con todas las variables.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="at">memory.profiling =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>modelo_todas_cv <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(clasificacion_Caras <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">family =</span> binomial, <span class="at">trControl =</span> cv)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="cn">NULL</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>pm1 <span class="ot">&lt;-</span> <span class="fu">summaryRprof</span>(<span class="at">memory =</span> <span class="st">"both"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>AIC1 <span class="ot">&lt;-</span> <span class="fu">AIC</span>(modelo_todas_cv<span class="sc">$</span>finalModel)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>BIC1 <span class="ot">&lt;-</span> <span class="fu">BIC</span>(modelo_todas_cv<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_todas_cv)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_summary, <span class="at">signif.stars =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Deviance Residuals: 
      Min         1Q     Median         3Q        Max  
-1.06e-04  -2.00e-08  -2.00e-08   2.00e-08   9.33e-05  

Coefficients: (9 not defined because of singularities)
                     Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)          1.88e+02   4.75e+07       0        1
SalePrice            2.39e+02   7.86e+04       0        1
LotFrontage          9.51e+00   4.46e+04       0        1
LotArea             -2.29e+01   7.81e+04       0        1
OverallQual         -5.54e+00   4.02e+04       0        1
OverallCond         -7.62e+00   3.32e+04       0        1
MasVnrArea          -9.07e+00   2.09e+04       0        1
BsmtFinSF1          -2.50e+01   7.21e+04       0        1
BsmtFinSF2          -4.51e+00   3.55e+04       0        1
BsmtUnfSF           -2.26e+01   6.36e+04       0        1
TotalBsmtSF                NA         NA      NA       NA
X1stFlrSF           -2.54e+01   5.60e+04       0        1
X2ndFlrSF            1.50e+01   8.01e+04       0        1
LowQualFinSF         1.74e+01   3.64e+04       0        1
GrLivArea                  NA         NA      NA       NA
BsmtFullBath        -3.98e+00   1.45e+04       0        1
BsmtHalfBath         1.19e+00   1.84e+04       0        1
FullBath            -4.26e+00   3.71e+04       0        1
HalfBath             5.39e+00   5.90e+04       0        1
BedroomAbvGr         2.73e+00   2.87e+04       0        1
KitchenAbvGr         1.32e+01   1.02e+05       0        1
TotRmsAbvGrd        -1.24e+00   5.26e+04       0        1
Fireplaces           5.89e+00   2.11e+04       0        1
GarageCars           8.58e+00   5.24e+04       0        1
GarageArea           5.29e+00   4.83e+04       0        1
WoodDeckSF           4.64e-01   1.82e+04       0        1
OpenPorchSF         -6.06e+00   3.43e+04       0        1
EnclosedPorch       -1.45e+01   1.93e+04       0        1
X3SsnPorch          -1.41e+00   1.57e+04       0        1
ScreenPorch         -1.27e+01   2.40e+04       0        1
PoolArea            -7.33e-01   1.42e+04       0        1
MiscVal              9.27e+00   1.79e+04       0        1
MSZoningFV          -9.92e+01   7.33e+05       0        1
MSZoningRH          -1.28e+02   6.39e+05       0        1
MSZoningRL          -1.29e+02   6.58e+05       0        1
MSZoningRM          -1.21e+02   5.79e+05       0        1
StreetPave           7.00e+01   6.54e+05       0        1
LandContourHLS      -5.57e+01   2.35e+05       0        1
LandContourLow      -3.29e+01   6.51e+05       0        1
LandContourLvl      -4.56e+01   2.05e+05       0        1
LotConfigCulDSac     3.15e+00   2.57e+05       0        1
LotConfigFR2        -3.51e+00   7.46e+04       0        1
LotConfigFR3        -2.97e+01   4.78e+05       0        1
LotConfigInside     -1.87e+01   4.09e+04       0        1
LandSlopeMod         2.01e+01   1.81e+05       0        1
LandSlopeSev         8.67e+01   4.95e+05       0        1
NeighborhoodBlueste  7.44e+01   3.42e+05       0        1
NeighborhoodBrDale   2.00e+02   2.14e+05       0        1
NeighborhoodBrkSide  6.93e+01   2.79e+05       0        1
NeighborhoodClearCr  5.35e+01   2.00e+05       0        1
NeighborhoodCollgCr  5.80e+01   1.64e+05       0        1
NeighborhoodCrawfor  4.08e+01   2.60e+05       0        1
NeighborhoodEdwards  1.64e+01   1.53e+05       0        1
NeighborhoodGilbert  1.62e+01   1.64e+05       0        1
NeighborhoodIDOTRR   7.26e+01   3.43e+05       0        1
NeighborhoodMeadowV  1.04e+02   3.29e+05       0        1
NeighborhoodMitchel  6.28e+01   2.32e+05       0        1
NeighborhoodNAmes    6.57e+01   1.62e+05       0        1
NeighborhoodNoRidge  4.48e+01   2.40e+05       0        1
NeighborhoodNPkVill  1.10e+02   2.08e+05       0        1
NeighborhoodNridgHt  4.08e+01   1.42e+05       0        1
NeighborhoodNWAmes   6.04e+01   1.56e+05       0        1
NeighborhoodOldTown  1.06e+02   3.01e+05       0        1
NeighborhoodSawyer   8.74e+01   1.67e+05       0        1
NeighborhoodSawyerW  4.65e+01   1.51e+05       0        1
NeighborhoodSomerst  1.72e+01   2.71e+05       0        1
NeighborhoodStoneBr  5.92e+01   1.41e+05       0        1
NeighborhoodSWISU    7.59e+01   2.60e+05       0        1
NeighborhoodTimber   7.14e+01   1.65e+05       0        1
NeighborhoodVeenker -8.37e+01   4.74e+05       0        1
BldgType2fmCon      -2.80e+01   4.36e+05       0        1
BldgTypeDuplex      -5.14e+01   5.51e+05       0        1
BldgTypeTwnhs        8.32e+00   1.66e+05       0        1
BldgTypeTwnhsE       5.80e+00   1.10e+05       0        1
HouseStyle1.5Unf     6.86e+01   3.68e+05       0        1
HouseStyle1Story     7.68e+01   1.69e+05       0        1
HouseStyle2.5Fin    -2.07e+02   3.74e+05       0        1
HouseStyle2.5Unf    -1.41e+02   7.50e+05       0        1
HouseStyle2Story    -2.64e+01   1.30e+05       0        1
HouseStyleSFoyer     6.30e+01   2.32e+05       0        1
HouseStyleSLvl       1.53e+01   1.76e+05       0        1
MasVnrTypeBrkFace    4.07e+01   3.94e+05       0        1
MasVnrTypeNone       3.04e+01   3.99e+05       0        1
MasVnrTypeStone      5.48e+01   3.93e+05       0        1
ExterQualFa          9.46e+01   6.38e+05       0        1
ExterQualGd          4.06e+01   2.69e+05       0        1
ExterQualTA          4.22e+01   2.95e+05       0        1
ExterCondFa          8.27e+01   4.75e+07       0        1
ExterCondGd          7.32e+01   4.75e+07       0        1
ExterCondPo                NA         NA      NA       NA
ExterCondTA          7.02e+01   4.75e+07       0        1
FoundationCBlock    -3.26e+01   1.77e+05       0        1
FoundationPConc     -3.17e+01   1.84e+05       0        1
FoundationSlab             NA         NA      NA       NA
FoundationStone      1.45e+01   1.28e+06       0        1
FoundationWood       1.94e+00   4.01e+05       0        1
BsmtCondGd           4.12e+01   3.04e+05       0        1
BsmtCondPo           1.58e+02   6.03e+05       0        1
BsmtCondTA           2.43e+01   2.74e+05       0        1
BsmtExposureGd       2.20e+01   5.24e+04       0        1
BsmtExposureMn       8.73e+00   5.02e+04       0        1
BsmtExposureNo       8.67e+00   2.75e+04       0        1
HeatingGasA         -2.84e+02   6.62e+05       0        1
HeatingGasW         -2.44e+02   7.08e+05       0        1
HeatingGrav                NA         NA      NA       NA
HeatingOthW                NA         NA      NA       NA
HeatingWall                NA         NA      NA       NA
HeatingQCFa         -3.18e+01   1.19e+05       0        1
HeatingQCGd         -1.81e+01   5.53e+04       0        1
HeatingQCPo          1.61e+02   4.74e+05       0        1
HeatingQCTA          9.30e+00   6.37e+04       0        1
CentralAirY         -2.53e+01   2.55e+05       0        1
ElectricalFuseF      1.96e+01   2.83e+05       0        1
ElectricalFuseP      1.74e+01   1.20e+06       0        1
ElectricalMix              NA         NA      NA       NA
ElectricalSBrkr     -2.18e+01   1.04e+05       0        1
KitchenQualFa        6.51e+01   2.97e+05       0        1
KitchenQualGd        5.01e+01   2.08e+05       0        1
KitchenQualTA        6.61e+01   2.27e+05       0        1
FunctionalMaj2      -2.56e+01   4.58e+05       0        1
FunctionalMin1      -3.01e+01   3.65e+05       0        1
FunctionalMin2      -2.85e+01   4.15e+05       0        1
FunctionalMod       -1.06e+02   9.63e+05       0        1
FunctionalSev              NA         NA      NA       NA
FunctionalTyp       -3.22e+01   2.40e+05       0        1
GarageFinishRFn     -8.06e+00   4.24e+04       0        1
GarageFinishUnf      1.87e+00   5.79e+04       0        1
PavedDriveP         -2.09e+01   2.47e+05       0        1
PavedDriveY         -2.54e+01   1.02e+05       0        1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9.8328e+02  on 764  degrees of freedom
Residual deviance: 1.1399e-07  on 645  degrees of freedom
AIC: 240

Number of Fisher Scoring iterations: 25</code></pre>
</div>
</div>
<p>El modelo indica la significancia de las variable con un *</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>variables_significativas <span class="ot">&lt;-</span> model_summary<span class="sc">$</span>coefficients[model_summary<span class="sc">$</span>coefficients[, <span class="dv">4</span>] <span class="sc">&lt;</span> <span class="fl">0.01</span>, , drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>columnas_significativas <span class="ot">&lt;-</span> <span class="fu">rownames</span>(variables_significativas[<span class="fu">order</span>(<span class="fu">abs</span>(variables_significativas[, <span class="dv">1</span>]), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>columnas_significativas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<p>Como se puede observar al tener el modelo con todas las variables se obteiene que ninguna variable es significativa, por lo tanto se procedió a realizar el modelo con las variables numericas para observar si estas tienen más significancia. Previo a esto se realizó un análisis de correlación entre las variables y se observó que tan bien se ajusta este modelo realizado.</p>
<section id="análisis-de-correlación-y-ajuste-de-modelo" class="level4">
<h4 class="anchored" data-anchor-id="análisis-de-correlación-y-ajuste-de-modelo">3.1.1 Análisis de correlación y ajuste de modelo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>datos_cor <span class="ot">&lt;-</span> datos_con_dummy[, numeric_variables]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>datos_cor <span class="ot">&lt;-</span> <span class="fu">select</span>(datos_cor, <span class="sc">-</span>SalePrice)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>correlacion <span class="ot">&lt;-</span> <span class="fu">cor</span>(datos_cor)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(correlacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MD_HDT6_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Existe correlación entre las siguientes variables:</p>
<ul>
<li>LotFrontage: LotArea, TotalBsmtSF, X1stFlrSF</li>
<li>LotArea: LotFrontage, TotalBsmtSF, GrLivArea</li>
<li>OverallQual: TotalBsmtSF, X1stFlrSF, GrLivArea, FullBath, GarageCars, GarageArea</li>
<li>BsmtFinSF1: BsmtUnfSF, BsmtFullBath</li>
<li>BsmtUnfSF: BsmtFinSF1</li>
<li>TotalsmtSF: X1stFlrSF</li>
<li>X1stFlrSF: TotalBsmtSF</li>
<li>X2ndFlrSF: GrLivArea</li>
<li>GrLivArea: X2ndFlrSF, TotRmsAbvGrd</li>
<li>BsmtFullBath: BsmtFinSF1</li>
<li>BedRoomAvGr: TotRmsAbvGr</li>
<li>TotRmsAbvGrd: OverallQual, X2ndFlrSF, FullBath, BedroomAbvGr</li>
<li>FirePlaces: OverallQual, X1stFlrSF, GrLivArea</li>
<li>GarageCars: OverallQual, TotalBsmtSF, X1stFlrSF, GrLivArea, FullBath, TotRmsAbvGrd, GarageArea</li>
<li>GarageArea: OverallQual, TotalBsmtSF, X1stFlrSF, GrLivArea, FullBath, TotRmsAbvGrd, GarageCars</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>test_1 <span class="ot">&lt;-</span> <span class="fu">select</span>(test, <span class="sc">-</span>clasificacion_Caras)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_todas_cv, <span class="at">newdata =</span> test_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
prediction from a rank-deficient fit may be misleading</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(pred), <span class="fu">as.factor</span>(test<span class="sc">$</span>clasificacion_Caras))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 206   9
         1  12 102
                                          
               Accuracy : 0.9362          
                 95% CI : (0.9041, 0.9601)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.8582          
                                          
 Mcnemar's Test P-Value : 0.6625          
                                          
            Sensitivity : 0.9450          
            Specificity : 0.9189          
         Pos Pred Value : 0.9581          
         Neg Pred Value : 0.8947          
             Prevalence : 0.6626          
         Detection Rate : 0.6261          
   Detection Prevalence : 0.6535          
      Balanced Accuracy : 0.9319          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>Parece ser que se tiene un buen modelo porque se tiene un accuracy de 0.87. La sensitividad y especificidad son buenas, de 0.89 y 0.83 respectivamente. Algo importante que se debe mencionar es que AIC es bastante alto, de 2717. Como se indicó, el modelo parece ajustarse bien a los datos, pero es necesario analizar el overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># train &lt;- train[, numeric_variables2]</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">&lt;-</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train, <span class="at">target =</span> <span class="st">"clasificacion_Caras"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in makeTask(type = type, data = data, weights = weights,
blocking = blocking, : Empty factor levels were dropped for columns:
ExterCond,Foundation,Heating,Functional</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">&lt;-</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">10</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">&lt;-</span> <span class="fu">makeLearner</span>(<span class="st">"classif.multinom"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">&lt;-</span> <span class="fu">generateLearningCurveData</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">learners =</span> lrn, <span class="at">task =</span> datos.task,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)), <span class="at">resampling =</span> rin2,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">show.info =</span> <span class="cn">FALSE</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MD_HDT6_files/figure-html/curva_de_aprendizaje-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al tener el accuracy con un 86% y al observar las curvas de aprendizaje se puede concluir que el modelo tiene overfitting. La curva de balance de error en training siempre está en 0 y nunca converge con la curva de test. Con un accuracy tan alto y pocas variables significativas, se concluye lo mencionado.</p>
</section>
</section>
<section id="modelo-con-variables-numéricas" class="level3">
<h3 class="anchored" data-anchor-id="modelo-con-variables-numéricas">3.2 Modelo con variables numéricas</h3>
<section id="creación-de-modelo" class="level4">
<h4 class="anchored" data-anchor-id="creación-de-modelo">3.2.1 Creación de modelo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>numeric_variables2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"LotFrontage"</span>, <span class="st">"LotArea"</span>, <span class="st">"OverallQual"</span>, <span class="st">"OverallCond"</span>, <span class="st">"MasVnrArea"</span>, <span class="st">"BsmtFinSF1"</span>, <span class="st">"BsmtFinSF2"</span>, <span class="st">"BsmtUnfSF"</span>, <span class="st">"TotalBsmtSF"</span>, <span class="st">"X1stFlrSF"</span>, <span class="st">"X2ndFlrSF"</span>, <span class="st">"LowQualFinSF"</span>, <span class="st">"GrLivArea"</span>, <span class="st">"BsmtFullBath"</span>, <span class="st">"BsmtHalfBath"</span>, <span class="st">"FullBath"</span>, <span class="st">"HalfBath"</span>, <span class="st">"BedroomAbvGr"</span>, <span class="st">"KitchenAbvGr"</span>, <span class="st">"TotRmsAbvGrd"</span>, <span class="st">"Fireplaces"</span>, <span class="st">"GarageCars"</span>, <span class="st">"GarageArea"</span>, <span class="st">"WoodDeckSF"</span>, <span class="st">"OpenPorchSF"</span>, <span class="st">"EnclosedPorch"</span>, <span class="st">"X3SsnPorch"</span>, <span class="st">"ScreenPorch"</span>, <span class="st">"PoolArea"</span>, <span class="st">"MiscVal"</span>, <span class="st">"clasificacion_Caras"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># datos_num &lt;- select(datos_con_dummy, -SalePrice)</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># datos_num &lt;- select(datos_con_dummy, -Utilities)</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>datos_num <span class="ot">&lt;-</span> datos_con_dummy[, numeric_variables2]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(datos_num), <span class="fu">nrow</span>(datos_num) <span class="sc">*</span> porcentaje)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> datos_num[corte, ]</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> datos_num[<span class="sc">-</span>corte, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="at">memory.profiling =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>modelo_todas_cv <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(clasificacion_Caras <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">family =</span> binomial, <span class="at">trControl =</span> cv)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="cn">NULL</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>pm2 <span class="ot">&lt;-</span> <span class="fu">summaryRprof</span>(<span class="at">memory =</span> <span class="st">"both"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>AIC2 <span class="ot">&lt;-</span> <span class="fu">AIC</span>(modelo_todas_cv<span class="sc">$</span>finalModel)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>BIC2 <span class="ot">&lt;-</span> <span class="fu">BIC</span>(modelo_todas_cv<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>model_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_todas_cv)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_summary, <span class="at">signif.stars =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-6.468  -0.235  -0.044   0.124   2.430  

Coefficients: (2 not defined because of singularities)
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -2.5159     0.2754   -9.13  &lt; 2e-16 ***
LotFrontage     0.0656     0.1780    0.37   0.7125    
LotArea         0.4336     0.2955    1.47   0.1423    
OverallQual     2.1617     0.3248    6.66  2.8e-11 ***
OverallCond     0.2925     0.1995    1.47   0.1426    
MasVnrArea     -0.2773     0.2099   -1.32   0.1866    
BsmtFinSF1      1.1210     0.5076    2.21   0.0272 *  
BsmtFinSF2      0.3277     0.2044    1.60   0.1088    
BsmtUnfSF       1.2663     0.4724    2.68   0.0074 ** 
TotalBsmtSF         NA         NA      NA       NA    
X1stFlrSF       0.5993     0.4476    1.34   0.1806    
X2ndFlrSF       0.9837     0.3927    2.50   0.0123 *  
LowQualFinSF   -0.1850     0.3094   -0.60   0.5500    
GrLivArea           NA         NA      NA       NA    
BsmtFullBath    0.5332     0.2290    2.33   0.0199 *  
BsmtHalfBath    0.1198     0.1493    0.80   0.4223    
FullBath        0.7172     0.2474    2.90   0.0037 ** 
HalfBath        0.3198     0.2341    1.37   0.1719    
BedroomAbvGr   -0.0549     0.2476   -0.22   0.8244    
KitchenAbvGr   -0.4582     0.2981   -1.54   0.1243    
TotRmsAbvGrd    0.1111     0.3664    0.30   0.7616    
Fireplaces      0.0876     0.1772    0.49   0.6208    
GarageCars      0.3489     0.4230    0.82   0.4095    
GarageArea      0.6500     0.4069    1.60   0.1102    
WoodDeckSF      0.0218     0.1625    0.13   0.8930    
OpenPorchSF     0.1952     0.1622    1.20   0.2290    
EnclosedPorch  -0.3416     0.2063   -1.66   0.0977 .  
X3SsnPorch      0.1160     0.1105    1.05   0.2936    
ScreenPorch    -0.0355     0.1558   -0.23   0.8197    
PoolArea       -0.9021     0.3051   -2.96   0.0031 ** 
MiscVal         0.3412     0.1542    2.21   0.0269 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 983.28  on 764  degrees of freedom
Residual deviance: 326.48  on 736  degrees of freedom
AIC: 384.5

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>Como se puede observar el modelo indica la significancia de las variable con un *, pero nosotros designamos las varibales que tienen un valor de significaia menor a 0.01, las cuales son:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>variables_significativas <span class="ot">&lt;-</span> model_summary<span class="sc">$</span>coefficients[model_summary<span class="sc">$</span>coefficients[, <span class="dv">4</span>] <span class="sc">&lt;</span> <span class="fl">0.01</span>, , drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>columnas_significativas <span class="ot">&lt;-</span> <span class="fu">rownames</span>(variables_significativas[<span class="fu">order</span>(<span class="fu">abs</span>(variables_significativas[, <span class="dv">1</span>]), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ])</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>columnas_significativas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "(Intercept)" "OverallQual" "BsmtUnfSF"   "PoolArea"    "FullBath"   </code></pre>
</div>
</div>
<p>Como se puede hay varias variables que son significativas para el modelo, con lo que teniendo eliminadas las columnas que no aportan al modelo. Hay otras variables como TotalBsmtSF y GrLivArea que no aportan nada al modelo.</p>
</section>
<section id="análisis-de-ajuste-de-modelo" class="level4">
<h4 class="anchored" data-anchor-id="análisis-de-ajuste-de-modelo">3.2.2 Análisis de ajuste de modelo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>test_1 <span class="ot">&lt;-</span> <span class="fu">select</span>(test, <span class="sc">-</span>clasificacion_Caras)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_todas_cv, <span class="at">newdata =</span> test_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
prediction from a rank-deficient fit may be misleading</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>cf1 <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(pred), <span class="fu">as.factor</span>(test<span class="sc">$</span>clasificacion_Caras))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Parece ser que se tiene un buen modelo porque se tiene un accuracy de 0.89. La sensitividad y especificidad son buenas, de 0.89 y 0.83 respectivamente. Algo importante que se debe mencionar es que AIC es bastante alto, de 2717. Como se indicó, el modelo parece ajustarse bien a los datos, pero es necesario analizar el overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">&lt;-</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train, <span class="at">target =</span> <span class="st">"clasificacion_Caras"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">&lt;-</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">10</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">&lt;-</span> <span class="fu">makeLearner</span>(<span class="st">"classif.multinom"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">&lt;-</span> <span class="fu">generateLearningCurveData</span>(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">learners =</span> lrn, <span class="at">task =</span> datos.task,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)), <span class="at">resampling =</span> rin2,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">show.info =</span> <span class="cn">FALSE</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MD_HDT6_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al tener el accuracy con un 89% y al observar las curvas de aprendizaje se puede concluir que el modelo tiene NO tiene overfitting. La curva de balance de error en training y de test convergen en cierto punto y se quedan relativamente constantes. Esto es lo que indica que tanto test como train son similares, por lo que es probable que NO haya overfitting con las variables numéricas únicamente.</p>
</section>
</section>
<section id="dos-modelos-adicionales-cambiando-variables-predictoras." class="level3">
<h3 class="anchored" data-anchor-id="dos-modelos-adicionales-cambiando-variables-predictoras.">7. Dos modelos adicionales cambiando variables predictoras.</h3>
<section id="primer-modelo" class="level4">
<h4 class="anchored" data-anchor-id="primer-modelo">7.1 Primer modelo</h4>
</section>
<section id="creación-de-modelo-1" class="level4">
<h4 class="anchored" data-anchor-id="creación-de-modelo-1">7.1.1 Creación de modelo</h4>
<p>Luego de observar las variables significativas numéricas se utilizarán OverallQual, BsmtFinSF1, BsmtUnfSF, X2ndFlrSF, Fullbath, PoolArea, MiscVal y BsmtFullBath porque son las que indican significancia en el modelo. Además, de las cualitativas se usarán Neighborhood, HouseStyle, Heating, Electrical, KitchenQual, LotConfig y ExterCond. A pesar de que las cualitativas no dieron nivel de significancia, pero se probará con las mencionadas porque pueden tener influencia al momento de darle valor a una casa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>variables_m1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"OverallQual"</span>, <span class="st">"BsmtFinSF1"</span>, <span class="st">"BsmtUnfSF"</span>, <span class="st">"X2ndFlrSF"</span>, <span class="st">"BsmtFullBath"</span>, <span class="st">"FullBath"</span>, <span class="st">"PoolArea"</span>, <span class="st">"MiscVal"</span>, <span class="st">"Neighborhood"</span>, <span class="st">"HouseStyle"</span>, <span class="st">"Heating"</span>, <span class="st">"Electrical"</span>, <span class="st">"KitchenQual"</span>, <span class="st">"LotConfig"</span>, <span class="st">"ExterCond"</span>, <span class="st">"clasificacion_Caras"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># datos_num &lt;- select(datos_con_dummy, -SalePrice)</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># datos_num &lt;- select(datos_con_dummy, -Utilities)</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>datos_m1 <span class="ot">&lt;-</span> datos_con_dummy[, variables_m1]</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(datos_m1), <span class="fu">nrow</span>(datos_m1) <span class="sc">*</span> porcentaje)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> datos_m1[corte, ]</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> datos_m1[<span class="sc">-</span>corte, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="at">memory.profiling =</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>modelo_todas_cv <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(clasificacion_Caras <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">family =</span> binomial, <span class="at">trControl =</span> cv)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="cn">NULL</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>pm3 <span class="ot">&lt;-</span> <span class="fu">summaryRprof</span>(<span class="at">memory =</span> <span class="st">"both"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>AIC3 <span class="ot">&lt;-</span> <span class="fu">AIC</span>(modelo_todas_cv<span class="sc">$</span>finalModel)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>BIC3 <span class="ot">&lt;-</span> <span class="fu">BIC</span>(modelo_todas_cv<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_todas_cv)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_summary, <span class="at">signif.stars =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-8.490  -0.148  -0.003   0.087   2.547  

Coefficients: (3 not defined because of singularities)
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          2.55e+13   1.94e+14    0.13  0.89543    
OverallQual          2.05e+00   3.84e-01    5.33  9.7e-08 ***
BsmtFinSF1           9.74e-01   3.25e-01    3.00  0.00274 ** 
BsmtUnfSF            6.73e-01   3.28e-01    2.05  0.04026 *  
X2ndFlrSF            4.56e+00   8.70e-01    5.24  1.6e-07 ***
BsmtFullBath         2.02e-01   2.44e-01    0.83  0.40785    
FullBath             4.92e-01   2.76e-01    1.78  0.07482 .  
PoolArea            -1.11e+00   2.90e-01   -3.82  0.00013 ***
MiscVal              3.71e-01   1.62e-01    2.29  0.02180 *  
NeighborhoodBlueste -2.09e+01   2.40e+05    0.00  0.99993    
NeighborhoodBrDale   4.87e-01   8.22e+00    0.06  0.95276    
NeighborhoodBrkSide  4.31e+00   1.52e+00    2.83  0.00464 ** 
NeighborhoodClearCr  2.09e+00   1.33e+00    1.57  0.11654    
NeighborhoodCollgCr  1.83e+00   8.89e-01    2.06  0.03965 *  
NeighborhoodCrawfor  3.24e+00   1.19e+00    2.71  0.00666 ** 
NeighborhoodEdwards -3.05e-01   1.42e+00   -0.21  0.82994    
NeighborhoodGilbert -3.09e-01   1.10e+00   -0.28  0.77851    
NeighborhoodIDOTRR  -1.87e+01   5.79e+04    0.00  0.99974    
NeighborhoodMeadowV -2.34e+01   1.19e+05    0.00  0.99984    
NeighborhoodMitchel  1.60e+00   1.38e+00    1.16  0.24729    
NeighborhoodNAmes    1.30e+00   1.09e+00    1.20  0.23184    
NeighborhoodNoRidge  1.59e+00   1.45e+00    1.09  0.27414    
NeighborhoodNPkVill -3.64e+01   1.32e+05    0.00  0.99978    
NeighborhoodNridgHt  1.87e+00   1.01e+00    1.84  0.06584 .  
NeighborhoodNWAmes   2.10e+00   1.05e+00    2.01  0.04474 *  
NeighborhoodOldTown -3.52e+00   2.94e+00   -1.20  0.23092    
NeighborhoodSawyer  -1.14e+01   8.25e+04    0.00  0.99989    
NeighborhoodSawyerW  1.44e+00   1.05e+00    1.37  0.17141    
NeighborhoodSomerst  2.04e+00   9.28e-01    2.19  0.02819 *  
NeighborhoodStoneBr  2.49e+01   8.47e+04    0.00  0.99977    
NeighborhoodSWISU   -2.86e+00   2.27e+00   -1.26  0.20759    
NeighborhoodTimber   7.50e-01   1.22e+00    0.62  0.53810    
NeighborhoodVeenker  1.36e+00   5.56e+00    0.24  0.80730    
HouseStyle1.5Unf    -1.02e+01   5.93e+04    0.00  0.99986    
HouseStyle1Story     8.02e+00   1.81e+00    4.42  9.7e-06 ***
HouseStyle2.5Fin     2.48e+00   2.05e+00    1.21  0.22555    
HouseStyle2.5Unf    -3.70e+00   6.45e+00   -0.57  0.56656    
HouseStyle2Story     5.25e-02   1.01e+00    0.05  0.95848    
HouseStyleSFoyer     7.10e+00   2.19e+00    3.25  0.00117 ** 
HouseStyleSLvl       9.72e-01   1.81e+00    0.54  0.59102    
HeatingGasA         -2.55e+13   1.94e+14   -0.13  0.89543    
HeatingGasW         -2.55e+13   1.94e+14   -0.13  0.89543    
HeatingGrav         -2.55e+13   1.94e+14   -0.13  0.89543    
HeatingOthW                NA         NA      NA       NA    
HeatingWall                NA         NA      NA       NA    
ElectricalFuseF     -1.97e+01   6.75e+04    0.00  0.99977    
ElectricalFuseP      3.68e+02   2.42e+06    0.00  0.99988    
ElectricalMix        2.27e+01   4.44e+05    0.00  0.99996    
ElectricalSBrkr      9.74e-01   1.28e+00    0.76  0.44748    
KitchenQualFa       -2.63e+01   6.01e+04    0.00  0.99965    
KitchenQualGd       -1.47e+00   1.10e+00   -1.34  0.18181    
KitchenQualTA       -2.75e+00   1.17e+00   -2.36  0.01844 *  
LotConfigCulDSac     3.05e+00   1.01e+00    3.04  0.00240 ** 
LotConfigFR2        -2.05e+00   9.94e-01   -2.06  0.03906 *  
LotConfigFR3        -1.01e+00   1.61e+00   -0.62  0.53292    
LotConfigInside     -2.01e-01   4.81e-01   -0.42  0.67524    
ExterCondFa         -2.12e+01   2.59e+04    0.00  0.99935    
ExterCondGd         -2.85e+00   6.86e+00   -0.42  0.67786    
ExterCondPo                NA         NA      NA       NA    
ExterCondTA         -2.38e+00   6.88e+00   -0.35  0.72985    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 983.28  on 764  degrees of freedom
Residual deviance: 417.83  on 708  degrees of freedom
AIC: 531.8

Number of Fisher Scoring iterations: 25</code></pre>
</div>
</div>
</section>
<section id="análisis-de-ajuste-de-modelo-1" class="level4">
<h4 class="anchored" data-anchor-id="análisis-de-ajuste-de-modelo-1">7.1.2 Análisis de ajuste de modelo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>test_1 <span class="ot">&lt;-</span> <span class="fu">select</span>(test, <span class="sc">-</span>clasificacion_Caras)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_todas_cv, <span class="at">newdata =</span> test_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
prediction from a rank-deficient fit may be misleading</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>cf2 <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(pred), <span class="fu">as.factor</span>(test<span class="sc">$</span>clasificacion_Caras))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>cf2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 201  13
         1  17  98
                                          
               Accuracy : 0.9088          
                 95% CI : (0.8724, 0.9376)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.7978          
                                          
 Mcnemar's Test P-Value : 0.5839          
                                          
            Sensitivity : 0.9220          
            Specificity : 0.8829          
         Pos Pred Value : 0.9393          
         Neg Pred Value : 0.8522          
             Prevalence : 0.6626          
         Detection Rate : 0.6109          
   Detection Prevalence : 0.6505          
      Balanced Accuracy : 0.9025          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>Al observar el accuracy del modelo, se puede observar que es de 0.91, un valor muy bueno. Además, el modelo es bueno para la identificación de verdaderos positivos y es ligeramente menos preciso para la identificación de verdaderos negativos. Sin embargo, parece ser un bueno modelo. Su AIC, de 531.8, es relativamente bajo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">&lt;-</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train, <span class="at">target =</span> <span class="st">"clasificacion_Caras"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in makeTask(type = type, data = data, weights = weights, blocking =
blocking, : Empty factor levels were dropped for columns: Heating,ExterCond</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">&lt;-</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">50</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">&lt;-</span> <span class="fu">makeLearner</span>(<span class="st">"classif.multinom"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">&lt;-</span> <span class="fu">generateLearningCurveData</span>(</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">learners =</span> lrn, <span class="at">task =</span> datos.task,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)), <span class="at">resampling =</span> rin2,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">show.info =</span> <span class="cn">FALSE</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MD_HDT6_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar que tanto la curva de entrenamiento como la de prueba, se van estabilizando al llegar al 100% de los datos. Además, ambas líneas son cercanas en valor. Esto puede indicar que el modelo no está haciendo overfitting.</p>
</section>
<section id="segundo-modelo" class="level4">
<h4 class="anchored" data-anchor-id="segundo-modelo">7.2 Segundo modelo</h4>
</section>
<section id="creación-de-modelo-2" class="level4">
<h4 class="anchored" data-anchor-id="creación-de-modelo-2">7.2.1 Creación de modelo</h4>
<p>Luego de observar las variables significativas del modelo anterior, se usará OverallQual, BsmtFinSF1, X2ndFlrSF, PoolArea, NeighborhoodBrkSide, NeighborhoodCrawfor, HouseStyle1Story, HouseStyleSFoyer y LotConfigCulDSac.Estas son las que más significancia tienen.</p>
<p>Para algunas variables categóricas se necesitará crear dummies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>datos_con_dummy2 <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(datos_con_dummy, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">"Neighborhood"</span>, <span class="st">"HouseStyle"</span>, <span class="st">"LotConfig"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>variables_m2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"OverallQual"</span>, <span class="st">"BsmtFinSF1"</span>, <span class="st">"BsmtUnfSF"</span>, <span class="st">"X2ndFlrSF"</span>, <span class="st">"PoolArea"</span>, <span class="st">"MiscVal"</span>, <span class="st">"Neighborhood_BrkSide"</span>, <span class="st">"Neighborhood_Crawfor"</span>, <span class="st">"HouseStyle_1Story"</span>, <span class="st">"HouseStyle_SFoyer"</span>, <span class="st">"LotConfig_CulDSac"</span>, <span class="st">"clasificacion_Caras"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>datos_m2 <span class="ot">&lt;-</span> datos_con_dummy2[, variables_m2]</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(datos_m2), <span class="fu">nrow</span>(datos_m2) <span class="sc">*</span> porcentaje)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> datos_m2[corte, ]</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> datos_m2[<span class="sc">-</span>corte, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>modelo_todas_cv <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(clasificacion_Caras <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">family =</span> binomial, <span class="at">trControl =</span> cv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_todas_cv)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_summary, <span class="at">signif.stars =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-4.999  -0.284  -0.073   0.142   2.576  

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)            -5.362      0.734   -7.30  2.8e-13 ***
OverallQual             2.881      0.299    9.65  &lt; 2e-16 ***
BsmtFinSF1              1.325      0.281    4.72  2.4e-06 ***
BsmtUnfSF               0.842      0.264    3.19  0.00140 ** 
X2ndFlrSF               3.468      0.543    6.39  1.7e-10 ***
PoolArea               -0.775      0.314   -2.47  0.01347 *  
MiscVal                 0.270      0.147    1.83  0.06651 .  
Neighborhood_BrkSide    2.073      0.774    2.68  0.00739 ** 
Neighborhood_Crawfor    1.093      0.661    1.65  0.09836 .  
HouseStyle_1Story       5.861      1.144    5.12  3.0e-07 ***
HouseStyle_SFoyer       4.858      1.648    2.95  0.00319 ** 
LotConfig_CulDSac       2.696      0.800    3.37  0.00075 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 983.28  on 764  degrees of freedom
Residual deviance: 362.33  on 753  degrees of freedom
AIC: 386.3

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="análisis-de-ajuste-de-modelo-2" class="level4">
<h4 class="anchored" data-anchor-id="análisis-de-ajuste-de-modelo-2">7.2.2 Análisis de ajuste de modelo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>test_1 <span class="ot">&lt;-</span> <span class="fu">select</span>(test, <span class="sc">-</span>clasificacion_Caras)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_todas_cv, <span class="at">newdata =</span> test_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cf3 <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(pred), <span class="fu">as.factor</span>(test<span class="sc">$</span>clasificacion_Caras))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>cf3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 204  20
         1  14  91
                                          
               Accuracy : 0.8967          
                 95% CI : (0.8586, 0.9274)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.7658          
                                          
 Mcnemar's Test P-Value : 0.3912          
                                          
            Sensitivity : 0.9358          
            Specificity : 0.8198          
         Pos Pred Value : 0.9107          
         Neg Pred Value : 0.8667          
             Prevalence : 0.6626          
         Detection Rate : 0.6201          
   Detection Prevalence : 0.6809          
      Balanced Accuracy : 0.8778          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>Al observar el accuracy del modelo, se puede observar que es de 0.9, un valor muy bueno. Además, el modelo es bueno para la identificación de verdaderos positivos pero no lo es tanto para la identificación de valores verdaderamente falsos. Sin embargo, parece ser un bueno modelo. Su AIC, de 386.3, es relativamente bajo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">&lt;-</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train, <span class="at">target =</span> <span class="st">"clasificacion_Caras"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">&lt;-</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">50</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">&lt;-</span> <span class="fu">makeLearner</span>(<span class="st">"classif.multinom"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">&lt;-</span> <span class="fu">generateLearningCurveData</span>(</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">learners =</span> lrn, <span class="at">task =</span> datos.task,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)), <span class="at">resampling =</span> rin2,</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">show.info =</span> <span class="cn">FALSE</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MD_HDT6_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar que la curva de entrenamiento se va estabilizando al llegar al 100% de los datos. Sin embargo, la curva de prueba no se estabiliza y tiene un aumento cerca del 100%, lo cual indica que el modelo tiene overfitting. En este caso, usar las mejores variables del modelo anterior no fue adecuado.</p>
</section>
</section>
<section id="análisis-de-eficiencia-del-algoritmo" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-eficiencia-del-algoritmo">8. Análisis de eficiencia del algoritmo</h3>
<p>Matriz de confusión primer modelo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>cf1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 198  17
         1  20  94
                                          
               Accuracy : 0.8875          
                 95% CI : (0.8483, 0.9196)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.7501          
                                          
 Mcnemar's Test P-Value : 0.7423          
                                          
            Sensitivity : 0.9083          
            Specificity : 0.8468          
         Pos Pred Value : 0.9209          
         Neg Pred Value : 0.8246          
             Prevalence : 0.6626          
         Detection Rate : 0.6018          
   Detection Prevalence : 0.6535          
      Balanced Accuracy : 0.8776          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>Matriz de confusión segundo modelo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>cf2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 201  13
         1  17  98
                                          
               Accuracy : 0.9088          
                 95% CI : (0.8724, 0.9376)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.7978          
                                          
 Mcnemar's Test P-Value : 0.5839          
                                          
            Sensitivity : 0.9220          
            Specificity : 0.8829          
         Pos Pred Value : 0.9393          
         Neg Pred Value : 0.8522          
             Prevalence : 0.6626          
         Detection Rate : 0.6109          
   Detection Prevalence : 0.6505          
      Balanced Accuracy : 0.9025          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>Matriz de confusión tercer modelo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>cf3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 204  20
         1  14  91
                                          
               Accuracy : 0.8967          
                 95% CI : (0.8586, 0.9274)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.7658          
                                          
 Mcnemar's Test P-Value : 0.3912          
                                          
            Sensitivity : 0.9358          
            Specificity : 0.8198          
         Pos Pred Value : 0.9107          
         Neg Pred Value : 0.8667          
             Prevalence : 0.6626          
         Detection Rate : 0.6201          
   Detection Prevalence : 0.6809          
      Balanced Accuracy : 0.8778          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>El primer modelo obtuvo un accuracy de 0.93, con un buen valor de specificity y sensitivity. Sin embargo, tenía overfitting. El segundo modelo tuvo un accuracy de 0.91. Fue bueno para verdaderos positivos y un poco menos para verdaderos negativos. El tercer modelo tuvo el peor accuracy, de 0.9. Su sensitivity fue buena, de 0.94, por lo que es bueno para verdaderos positivos pero su specificity no fue muy buena, de 0.82.</p>
<p>Por otra parte, para el primer modelo su velocidad fue de 2.8 ms y su consumo de memoria 2.29754^{4} MB. Para el segundo modelo, 0.32 ms y 5801.4 MB. Para el tercer modelo 0.98 ms y 1.24336^{4} MB.</p>
</section>
<section id="determinación-de-que-modelo-es-mejor." class="level3">
<h3 class="anchored" data-anchor-id="determinación-de-que-modelo-es-mejor.">9. Determinación de que modelo es mejor.</h3>
<p>Se obtuvo el AIC y BIC para cada modelo. Para el primero modelo se obtuvo un AIC de 240.0000001 y un BIC de 796.7851002. Para el segundo modelo se obtuvo un AIC de 384.4769203 y un BIC de 519.0333195. Para el tercer modelo se obtuvo un AIC de 531.8277754 y un BIC de 796.3006979.</p>
<p>Se puede determinar que el segundo modelo es el mejor. Por un lado, se evidenció que no tiene overfitting. Su accuracy fue el segundo mejor, además el balance que tiene en la identificación de verdaderos positivos y verdaderos negativos, lo hace ser mejor que los otros dos modelos. Tiene la mejor velocidad y el menor uso de memoria de los tres. Finalmente, tiene el mejor balance entre AIC y BIC, siendo estos valores bastante bajos. El primer modelo tiene un AIC más bajo pero un BIC mucho más alto.</p>
</section>
<section id="creación-de-otros-modelos-adicionales." class="level3">
<h3 class="anchored" data-anchor-id="creación-de-otros-modelos-adicionales.">10. Creación de otros modelos adicionales.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># USEN ESTAS VARIABLES PARA PREDECIR EN LOS MODELOS</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>variables_models <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"LotFrontage"</span>, <span class="st">"LotArea"</span>, <span class="st">"OverallQual"</span>, <span class="st">"OverallCond"</span>, <span class="st">"MasVnrArea"</span>, <span class="st">"BsmtFinSF1"</span>, <span class="st">"BsmtFinSF2"</span>, <span class="st">"BsmtUnfSF"</span>, <span class="st">"TotalBsmtSF"</span>, <span class="st">"X1stFlrSF"</span>, <span class="st">"X2ndFlrSF"</span>, <span class="st">"LowQualFinSF"</span>, <span class="st">"GrLivArea"</span>, <span class="st">"BsmtFullBath"</span>, <span class="st">"BsmtHalfBath"</span>, <span class="st">"FullBath"</span>, <span class="st">"HalfBath"</span>, <span class="st">"BedroomAbvGr"</span>, <span class="st">"KitchenAbvGr"</span>, <span class="st">"TotRmsAbvGrd"</span>, <span class="st">"Fireplaces"</span>, <span class="st">"GarageCars"</span>, <span class="st">"GarageArea"</span>, <span class="st">"WoodDeckSF"</span>, <span class="st">"OpenPorchSF"</span>, <span class="st">"EnclosedPorch"</span>, <span class="st">"X3SsnPorch"</span>, <span class="st">"ScreenPorch"</span>, <span class="st">"PoolArea"</span>, <span class="st">"MiscVal"</span>, <span class="st">"clasificacion_Caras"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="árbol-de-decisión" class="level4">
<h4 class="anchored" data-anchor-id="árbol-de-decisión">10.1 Árbol de decisión</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="at">memory.profiling =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>modelo_arbol <span class="ot">&lt;-</span> <span class="fu">rpart</span>(clasificacion_Caras <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">maxdepth =</span> <span class="dv">4</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(modelo_arbol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MD_HDT6_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="cn">NULL</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>pm4 <span class="ot">&lt;-</span> <span class="fu">summaryRprof</span>(<span class="at">memory =</span> <span class="st">"both"</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_arbol, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(y_pred, test<span class="sc">$</span>clasificacion_Caras)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 211  37
         1   7  74
                                          
               Accuracy : 0.8663          
                 95% CI : (0.8246, 0.9011)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.6796          
                                          
 Mcnemar's Test P-Value : 1.232e-05       
                                          
            Sensitivity : 0.9679          
            Specificity : 0.6667          
         Pos Pred Value : 0.8508          
         Neg Pred Value : 0.9136          
             Prevalence : 0.6626          
         Detection Rate : 0.6413          
   Detection Prevalence : 0.7538          
      Balanced Accuracy : 0.8173          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
<section id="random-forest" class="level4">
<h4 class="anchored" data-anchor-id="random-forest">10.2 Random Forest</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="at">memory.profiling =</span> <span class="cn">TRUE</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>modeloRF <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(clasificacion_Caras <span class="sc">~</span> ., train, <span class="at">na.action =</span> na.omit)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="cn">NULL</span>)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>pm5 <span class="ot">&lt;-</span> <span class="fu">summaryRprof</span>(<span class="at">memory =</span> <span class="st">"both"</span>)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>ypred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modeloRF, <span class="at">newdata =</span> test)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>ypred <span class="ot">&lt;-</span> <span class="fu">factor</span>(ypred)</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(ypred, test<span class="sc">$</span>clasificacion_Caras)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 201  16
         1  17  95
                                         
               Accuracy : 0.8997         
                 95% CI : (0.862, 0.9299)
    No Information Rate : 0.6626         
    P-Value [Acc &gt; NIR] : &lt;2e-16         
                                         
                  Kappa : 0.7762         
                                         
 Mcnemar's Test P-Value : 1              
                                         
            Sensitivity : 0.9220         
            Specificity : 0.8559         
         Pos Pred Value : 0.9263         
         Neg Pred Value : 0.8482         
             Prevalence : 0.6626         
         Detection Rate : 0.6109         
   Detection Prevalence : 0.6596         
      Balanced Accuracy : 0.8889         
                                         
       'Positive' Class : 0              
                                         </code></pre>
</div>
</div>
</section>
<section id="naive-bayes" class="level4">
<h4 class="anchored" data-anchor-id="naive-bayes">10.3 Naive Bayes</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="at">memory.profiling =</span> <span class="cn">TRUE</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>modeloNB <span class="ot">&lt;-</span> <span class="fu">naiveBayes</span>(clasificacion_Caras <span class="sc">~</span> ., train)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Rprof</span>(<span class="cn">NULL</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>pm6 <span class="ot">&lt;-</span> <span class="fu">summaryRprof</span>(<span class="at">memory =</span> <span class="st">"both"</span>)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>ypred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modeloNB, <span class="at">newdata =</span> test)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>ypred <span class="ot">&lt;-</span> <span class="fu">factor</span>(ypred)</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(ypred, test<span class="sc">$</span>clasificacion_Caras)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 171  17
         1  47  94
                                          
               Accuracy : 0.8055          
                 95% CI : (0.7585, 0.8468)
    No Information Rate : 0.6626          
    P-Value [Acc &gt; NIR] : 7.107e-09       
                                          
                  Kappa : 0.592           
                                          
 Mcnemar's Test P-Value : 0.000289        
                                          
            Sensitivity : 0.7844          
            Specificity : 0.8468          
         Pos Pred Value : 0.9096          
         Neg Pred Value : 0.6667          
             Prevalence : 0.6626          
         Detection Rate : 0.5198          
   Detection Prevalence : 0.5714          
      Balanced Accuracy : 0.8156          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
</section>
<section id="comparación-de-eficiencia-entre-modelos." class="level3">
<h3 class="anchored" data-anchor-id="comparación-de-eficiencia-entre-modelos.">11. Comparación de eficiencia entre modelos.</h3>
<p>Podemos observar que el modelo de Random Forest es el que mejor desempeño tuvo con un accuracy de 0.899. El modelo de Naive Bayes tuvo un accuracy de 0.84 y el modelo de Arbol de Clasificacion tuvo un accuracy de 0.806. El que más tardó fue el Random Forest con un tiempo de 0.48. El arbol de Clasificacion tuvo la mayor cantidad de falsos positivos con un total de 37, mientras que el Naive Bayes tuvo la mayor cantidad de falsos negativos con un total de 35. El modelo que menos se equivocó fue el Random Forest, cosa que se puede observar tanto en la matriz de confusión como en el accuracy.<br>
Como se puede obserevar el que mejor accuracy tuvo y el que tuvo mejor desempeño sobre los otros fue también el que más se tardó, indicando que es un modelo más robusto y que se ajusta mejor a las variables que se están utilizando para predecir.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>